### ISSUE TITLE
AssertionError using piqa.SSIM

### ISSUE THREAD

**Issue by kanishk-aidash** [francois-rozet/piqa#19]
#### Getting AssertionError for computing SSIM value between a model predticted image and ground truth image

```
Traceback (most recent call last):  
File "train.py", line 133, in <module>    
    train(opt)  
File "train.py", line 69, in train    
    loss = criterion(labels, preds)  
File "/opt/ml/code/loss.py", line 90, in sr_loss
   l3 = SSIMLoss(y_true[:,0:3,:,:], y_pred[:,0:3,:,:]) 
 File "/opt/ml/code/loss.py", line 35, in SSIMLoss    
    return (1 - ssim(y_true, y_pred))  
File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl    
    return forward_call(*input, **kwargs)  
File "/opt/conda/lib/python3.6/site-packages/piqa/ssim.py", line 259, in forward    
    value_range=(0., self.value_range),  
File "/opt/conda/lib/python3.6/site-packages/piqa/utils/__init__.py", line 83, in _assert_type    
    'Expected values to be lower or equal to'
--
AssertionError: Expected values to be lower or equal to 1.0, got 1.242782473564148
```

#### Reproduce

A minimal working example demonstrating the current behavior.

```python
from piqa import SSIM

class SSIMLoss(SSIM):
    def forward(self, x, y):
        return 1. - super().forward(x, y)

criterion = SSIMLoss() # .cuda() if you need GPU support

...
loss = criterion(x, y)
...

```

#### Expected behavior

I have two doubts: 
1. Why is the module calculating SSIM > 1.0 
2. If it is, why is it getting caught as an assertion

#### Causes and solution

NA

#### Environment

* PIQA version: 1.1.7
* Python version: 3.6
* OS: MacOS Monterey 12.1

**Comment by francois-rozet** [comment]
Hello @kanishk-aidash,

By default, the value of the pixels is supposed to range from `0` to `1`. This is a very common default within the PyTorch vision community. You can change that with the `value_range` option in most metrics of PIQA. For instance, if your pixel values are between `0` and `255` you can do

```python
criterion = SSIMLoss(value_range=255.)
```

Alternatively, you can disable the assertions performed by PIQA (see [Assert](https://github.com/francois-rozet/piqa#assert) section).
