### ISSUE TITLE
[BUG] RuntimeError with piqa.MS_SSIM

### ISSUE THREAD

**Issue by trougnouf** [francois-rozet/piqa#25]
### Description

RuntimeError using MS_SSIM with updated PyTorch.

### Reproduce

```python
[trougnouf@uryzen:~]$ python                                                                                                                                                  (03-03 14:58)
Python 3.10.2 (main, Jan 15 2022, 19:56:27) [GCC 11.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> import piqa
>>> piqa.MS_SSIM()(torch.rand(1,3,256,256), torch.rand(1,3,256,256))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/lib/python3.10/site-packages/piqa/ssim.py", line 324, in forward
    l = ms_ssim(
  File "/usr/lib/python3.10/site-packages/piqa/ssim.py", line 180, in ms_ssim
    ss, cs = ssim(
  File "/usr/lib/python3.10/site-packages/piqa/ssim.py", line 100, in ssim
    mu_x = channel_convs(x, window, pad)
  File "/usr/lib/python3.10/site-packages/piqa/utils/functional.py", line 75, in channel_convs
    x = channel_conv(x, k)
  File "/usr/lib/python3.10/site-packages/piqa/utils/functional.py", line 39, in channel_conv
    return F.conv1d(x, kernel, padding=padding, groups=x.size(1))
RuntimeError: Expected 2D (unbatched) or 3D (batched) input to conv1d, but got input of size: [1, 3, 256, 256]

```

### Environment

* PIQA version: 1.1.7+4+g48ec8c4-1
* PyTorch version: 1.11.0rc3-1
* Cuda version: 11.6.0-1
* Python version: 3.10.2
* OS: Arch Linux

**Comment by francois-rozet** [comment]
Hello @trougnouf 👋 Thanks for the bug report!

In previous versions of PyTorch, `torch.nn.functional.conv1d` could be used to compute N-dimensional convolutions. I think this is not possible in 1.11 anymore due to API changes. I will have to fix that. However, I will wait for the stable version of 1.11 to be released to do so.
